version: 2

project_name: autonoe

monorepo:
  tag_prefix: cli-v

builds:
  - id: cli
    builder: bun
    binary: autonoe
    main: bin/autonoe.ts
    targets:
      - linux-x64-modern
      - linux-arm64
      - darwin-x64
      - darwin-arm64
      - windows-x64-modern
    flags:
      - --compile
      - --minify

archives:
  - id: cli
    builds: [cli]
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

release:
  mode: append

changelog:
  use: github-native
